import { Geist, Geist_Mono, Roboto, Road_Rage, Alatsi } from "next/font/google";
import "./globals.css";
import Providers from "../app/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roadRage = Road_Rage({
  variable: "--font-road-rage",
  subsets: ["latin"],
  weight: ["400"],
});

const roboto = Roboto({
  weight: ["400"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

const alatsi = Alatsi({
  weight: ["400"],
  variable: "--font-alatsi",
  subsets: ["latin"],
});

export const metadata = {
  title: "Conference Ticket Generator",
  description: "Generated by create next app",
  icons:{
    icon:"/thumb.ico", 
  } 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      <link rel="icon" href="/thumb.ico"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable}  ${roadRage.variable} ${alatsi.variable} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
